name: fireforest_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  image_picker: ^1.1.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  url_launcher: ^6.2.2
  intl: ^0.20.2
  google_maps_flutter: ^2.6.0
  cached_network_image: ^3.3.1
  image: ^4.0.17
  latlong2: ^0.9.0
  permission_handler: ^12.0.1
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true

fonts:
  - family: Kanit
    fonts:
      - asset: assets/fonts/Kanit-Regular.ttf
      - asset: assets/fonts/Kanit-Medium.ttf
        weight: 500
      - asset: assets/fonts/Kanit-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Kanit-Bold.ttf
        weight: 700

  - family: Sarabun
    fonts:
      - asset: assets/fonts/Sarabun-Regular.ttf
      - asset: assets/fonts/Sarabun-Medium.ttf
        weight: 500
      - asset: assets/fonts/Sarabun-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Sarabun-Bold.ttf
        weight: 700
